image: "coqorg/coq:latest"

build x86 minimal with digger:
  stage: build
  script:
    # get digger from latest CI artifacts
    - cd tools/digger
    - curl -L 'https://gitlab.univ-lille.fr/2xs/digger/-/jobs/artifacts/master/download?job=build' -o digger.zip
    - unzip -o digger.zip
    - cd ../..

    - .ci/apt-get.sh nasm gcc

    - ./configure.sh --architecture=x86 --partition-name=minimal --libpip=/tmp --no-command-check
    - make minimal.elf
  artifacts:
    paths:
      - minimal.elf
    expire_in: 1 hour

test x86 minimal:
  stage: test
  dependencies:
    - build x86 minimal with digger
  script:
    - .ci/apt-get.sh qemu-system-x86
    - ./configure.sh --architecture=x86 --partition-name=minimal --libpip=/tmp --no-command-check
    - make -o minimal.elf test-minimal

build arm minimal with digger:
  stage: build
  script:
    # get digger from latest CI artifacts
    - cd tools/digger
    - curl -L 'https://gitlab.univ-lille.fr/2xs/digger/-/jobs/artifacts/master/download?job=build' -o digger.zip
    - unzip -o digger.zip
    - cd ../..

    - .ci/apt-get.sh libnewlib-arm-none-eabi gcc-arm-none-eabi

    - ./configure.sh --architecture=armv7 --partition-name=minimal --libpip=/tmp --no-command-check
    - make minimal.elf
  artifacts:
    paths:
      - minimal.elf
    expire_in: 1 hour

test arm minimal:
  stage: test
  dependencies:
    - build arm minimal with digger
  script:
    - .ci/apt-get.sh qemu-system-arm
    - ./configure.sh --architecture=armv7 --partition-name=minimal --libpip=/tmp --no-command-check
    - make -o minimal.elf test-minimal

check proofs:
  when: manual
  script:
    - coqc --version
    - ./configure.sh --architecture=x86 --partition-name=minimal --libpip=/tmp --no-command-check
    - make proofs
