#ifndef SEGMENT_SELECTORS_H
#define SEGMENT_SELECTORS_H

#define USER_RING   0b11
#define KERNEL_RING 0b00

#define KERNEL_CODE_SEGMENT_SELECTOR 0x08
#define KERNEL_DATA_SEGMENT_SELECTOR 0x10
#define USER_CODE_SEGMENT_SELECTOR   0x18
#define USER_DATA_SEGMENT_SELECTOR   0x20
#define TSS_SELECTOR                 0x28

#endif
